#!/usr/bin/env python3
import datetime
import math # not used: makes script slower for no reason!

# generated by ChatGPT, 2025-11-19: result waxing crescent
# compare https://moonphases.co.uk/moon-calendar: result new moon on 19-11-25 (2 days difference)

def moon_phase_symbol(): #bad function name
    # Current date
    now = datetime.datetime.utcnow()
    # deprecated two years ago
    # cf https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated
    year = now.year
    month = now.month
    day = now.day

    # Conway's simplified moon phase algorithm
    if month < 3:
        year -= 1
        month += 12

    K1 = int(365.25 * (year + 4712))
    # why is the variable called K here?
    # why coerce to an integer here?
    # floats are used below anyway
    K2 = int(30.6 * (month + 1))
    K3 = int(int((year/100) + 49) * 0.75) - 38

    # Julian day approximation
    J = K1 + K2 + day + 59
    if J > 2299160:
        J -= K3

    # Moon phase (0–29.53 days)
    moon_age = (J - 2451550.1) / 29.53058867
    moon_age = moon_age % 1  # fraction of the cycle
    # why is the same variable name used twice?
    age_days = moon_age * 29.53
    # multiplying by a different float from two lines above - why?

    # Map age to Unicode symbols
    phases = [
        (1.0, "🌑 New Moon"),
        (6.3825, "🌒 Waxing Crescent"),
        (9.3825, "🌓 First Quarter"),
        (13.765, "🌔 Waxing Gibbous"),
        (16.765, "🌕 Full Moon"),
        (20.148, "🌖 Waning Gibbous"),
        (23.148, "🌗 Last Quarter"),
        (27.53, "🌘 Waning Crescent"),
        (29.53, "🌑 New Moon")
    ]

    for threshold, symbol in phases:
        # symbol is a misleading variable name
        if age_days <= threshold:
            return symbol

if __name__ == "__main__": # not needed
    print(moon_phase_symbol())
    # better to print today's date as well
    # for debugging purposes
    # although I didn't ask for that
